DROP DATABASE IF EXISTS `lab`;

CREATE DATABASE `lab`;

USE `lab`;

CREATE TABLE `student` (
    `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(20) UNIQUE NOT NULL,
    `age` TINYINT UNSIGNED NOT NULL
);

